version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - echo No build step needed

  post_build:
    commands:
      - echo Build completed successfully
