version: 0.2
phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install
  build:
    commands:
      - echo No build step needed
      - npm run build
artifacts:
  files:
    - '**/*'
